# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-27 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name=b'User Link')),
                ('email', models.CharField(max_length=100, verbose_name=b'Email')),
            ],
        ),
    ]
